trigger:
- master

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build_And_Test_Relay
    steps:
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Hsco_cert.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dev Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCOrelaydev.mobileprovision'
      displayName: Installing iOS Dev Mobile Provisioning Profile
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'HSCO-Distribution.p12'
        certPwd: '$(privateKeyPassword)'
      displayName: Installing iOS Dist Certificate
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'HSCOrelaydistribution.mobileprovision'
      displayName: Installing iOS Dist Mobile Provisioning Profile
    - task: DownloadSecureFile@1
      name: iosGoogleServices
      inputs:
        secureFile: 'GoogleService-Info.plist'
    - script: cp $(iosGoogleServices.secureFilePath) ios/Runner/GoogleService-Info.plist
    - task: DownloadSecureFile@1
      name: apiConstants
      inputs:
        secureFile: 'api_constants.dart'
    - script: |
        mkdir -p lib/secrets
        cp $(apiConstants.secureFilePath) lib/secrets/api_constants.dart
    - task: FlutterInstall@0
    - script: |
        echo $(FlutterToolPath)
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        echo $PATH
        flutter pub global activate pubspec_version
        [[ `pubver get` =~ ^[0-9]+.[0,1].0$ ]] && echo "It's a release, don't bump." || pubver bump patch
        pubver set `pubver get`+$(Build.BuildNumber)
        echo $(Agent.BuildDirectory)
        cd $(Agent.BuildDirectory)
        ls
      displayName: Increment build number.
    - script: |
        export PATH=$PATH:$(FlutterToolPath):$(FlutterToolPath)/cache/dart-sdk/bin:$(FlutterToolPath)/../.pub-cache/bin/
        flutter build ios
      displayName: Build iOS App.
#    - task: FlutterTest@0
#      inputs:
#        projectDirectory: '.'
#      displayName: Run Unit Tests.
    - script: /usr/bin/xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -archivePath build/ios/iphoneos/RelayRelease.xcarchive -configuration Release archive
      displayName: Archive iOS App
    - script: | 
        /usr/bin/xcodebuild -exportArchive -archivePath build/ios/iphoneos/RelayRelease.xcarchive -exportPath build/ios/iphoneos/ -exportOptionsPlist ios/ExportOptions.plist
        echo 'new alpha.' > build/ios/iphoneos/test_notes.txt
      displayName: Export iOS App
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build/ios/iphoneos'
        Contents: |
          *.ipa
          test_notes.txt
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(Build.BuildNumber)'
        publishLocation: 'pipeline'
    - script: |
        git config --global user.email "tk@hinterlandsupply.co"
        git config --global user.name "Azure DevOps CI"
        git add pubspec.yaml
        git commit -m "Updated Automated Build Number [skip ci]"
        git pull origin master --rebase
        git push https://$USERNAME:$PASSWORD@github.com/hinterlandsupplyco/RelayApp.git HEAD:master
      displayName: Push updated pubspec