name: relay
version: 1.1.1+6
description: A new Flutter project.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  get_it: ^4.0.1
  sembast: ^2.3.0
  path_provider: ^1.6.5
  provider: ^4.0.4
  i18n_extension: ^1.3.4
  flutter_focus_watcher: ^0.0.1
  contacts_service: ^0.3.10
  commons: ^0.7.6
  flare_flutter: ^2.0.1
  animated_text_kit: ^2.0.0
  auto_size_text: ^2.1.0
  rxdart: ^0.24.0
  flappy_search_bar: ^1.7.2
  uuid: ^2.0.4
  image: ^2.1.4
  path: ^1.6.4
  waiting_dialog: ^0.0.4
  flutter_slidable: ^0.5.4
  intl: ^0.16.0
  flutter_sms: 2.0.0+2
  lottie: ^0.3.3
  percent_indicator: ^2.1.1+1
  align_positioned: ^1.2.5
  assorted_layout_widgets: ^1.0.18
  hidden_drawer_menu: ^1.1.2
  line_awesome_icons: ^1.0.4+2
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  permission_handler: ^5.0.0+hotfix.3
  image_picker: ^0.6.5
  purchases_flutter: ^1.0.4
  vibration: ^1.2.4
  cupertino_icons: ^0.1.2
  flutter_localizations: 
    sdk: flutter
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_launcher_icons: ^0.7.4
  flutter_test: 
    sdk: flutter
flutter_icons: 
  image_path: assets/images/app_icon.png
  android: true
  ios: true
flutter: 
  assets: 
    - assets/animations/loading.flr
    - assets/animations/paper-flying-animation.json
    - assets/animations/splash_screen.flr
    - assets/animations/onboarding_create_profile.flr
    - assets/animations/onboarding_messaging.flr
    - assets/animations/onboarding_success.flr
    - assets/images/onboarding_profile.png
    - assets/images/onboarding_messaging.png
    - assets/images/onboarding0.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
  fonts: 
    - 
      family: Avenir
      fonts: 
        - 
          asset: fonts/Avenir-Heavy.ttf
        - 
          asset: fonts/Avenir-Book.ttf
  uses-material-design: true
